# DO NOT EDIT! This file is generated by resolve-components
# Usage: ./resolve-components [esp-X.Y.Z_YYYYMMDD]
# See: pkgs/development/espressif/resolve-components
{ lib }:

lib.fix (self: {
  release = "esp-16.2.0_20260914";

  fork = {
    gcc = "96666a8b989e784ad3356b013e77e94a530fafe7";
    binutils-gdb = "f5e7bfaf0786cd74c7138e32ca50359618967abf";
    picolibc = "acc7d70e974f4ef01cb946d58291cc3fe91c78b4";
    newlib = "795b14dd6568e36c02623a8329ac903cb4dbc835";
  };

  submodule = {
    overlays = "dd1cf19f6eb327a9db51043439974a6de13f5c7f";
    dynconfig = "c545876fb73c0ada60cb6413c61554f5b93d4e8a";
    bin-wrappers = "11094a6eb2b2e7893747faac49012d0e9fb76921";
  };

  # List all resolved SHAs as a flat attrset.
  allSHAs = self.fork // self.submodule;
})
